const list = [{
        id: 1,
        title: "Game Development : Gaming Design & Programming",
        author: "Paperback | 1 January 2021",
        price: 1199,
        img: "https://images-na.ssl-images-amazon.com/images/I/51ZgZWQhY5S._SX477_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 2,
        title: "Zero To Mastery In Python Programming",
        author: "Paperback | 21 July 2021",
        price: 1149,
        img: "https://images-na.ssl-images-amazon.com/images/I/51wFUIISd9S._SX377_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 3,
        title: "Amazing Questions & Answers Science",
        author: "by Om Books Editorial Team  | 25 November 2018",
        price: 2299,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 4,
        title: "Core Python Programming",
        author: "Paperback | 1 September 2021",
        price: 1249,
        img: "https://m.media-amazon.com/images/I/518csN6TPsL._BG0,0,0,0_FMpng_AC_SY320_SX320_.jpg",
        amount: 1,
    },
    {
        id: 5,
        title: "Data Analytics using Python ",
        author: "Paperback – 25 June 2020",
        price: 1299,
        img: "https://images-eu.ssl-images-amazon.com/images/I/41rniDM2CkL._SX198_BO1,204,203,200_QL40_FMwebp_.jpg",
        amount: 1,
    },
    {
        id: 6,
        title: "Python for Data Science For Dummies",
        author: "Paperback – 1 January 2019",
        price: 1349,
        img: "https://images-na.ssl-images-amazon.com/images/I/51QwUZms+uL._SX389_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 7,
        title: "Machine Learning using Python",
        author: "Paperback | 1 January 2019",
        price: 2399,
        img: "https://images-na.ssl-images-amazon.com/images/I/51bffNVIcmL._SX385_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 8,
        title: "Data Structures & Algorithms in Java",
        author: "Paperback – 1 January 2014",
        price: 2449,
        img: "https://images-na.ssl-images-amazon.com/images/I/51IqMKZgn+L._SX381_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 9,
        title: "Java 8 in Action ",
        author: "Paperback – 1 January 2014",
        price: 2499,
        img: "https://images-na.ssl-images-amazon.com/images/I/515CLRw4dBL._SX380_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 10,
        title: "Programming with Java | 6th Edition",
        author: "Paperback – 25 March 2019",
        price: 3549,
        img: "https://images-na.ssl-images-amazon.com/images/I/41Fji-VVHYL._SX380_BO1,204,203,200_.jpg",
        amount: 1,

    },
    {
        id: 11,
        title: "Programming in ANSI C",
        author: "Paperback – 25 March 2019",
        price: 2599,
        img: "https://images-na.ssl-images-amazon.com/images/I/5111biSmaxL._SX384_BO1,204,203,200_.jpg",
        amount: 1,
    },
    {
        id: 12,
        title: "Authentic Guide To C Programming Language ",
        author: "Paperback – 4 September 2020",
        price: 3649,
        img: "https://images-na.ssl-images-amazon.com/images/I/4157x3EFkkL._SX348_BO1,204,203,200_.jpg",
        amount: 1,
    },
];

export default list;